package sample;

import java.awt.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.DefaultListModel;


public class LegoStore extends javax.swing.JFrame {
    
    /**
     * Creates new form LegoStore
     */
    public LegoStore() {
        initComponents();
        Loginpane.setVisible(true);
        homepane.setVisible(false);
        searchpane.setVisible(false);
        cartpane.setVisible(false);
        myorderpane.setVisible(false);
        placingorderpane.setVisible(false);
        image1pane.setVisible(true);
        image2pane.setVisible(false);
        
        
    }
    
        static String col[]= {"Toy Code", "Name", "Price", "Qty Ordered", "Amount"};
      static String row[][];
            DefaultListModel model = new DefaultListModel();
            DefaultTableModel model1 = new DefaultTableModel(row,col);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Loginpane = new javax.swing.JLayeredPane();
        usernamelbl = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        passwordlbl = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        passwordpf = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        custnamelbl = new javax.swing.JLabel();
        custuserlbl = new javax.swing.JLabel();
        custpasslbl = new javax.swing.JLabel();
        custnametf = new javax.swing.JTextField();
        custusertf = new javax.swing.JTextField();
        createaccount = new javax.swing.JButton();
        custpasspf = new javax.swing.JPasswordField();
        homepane = new javax.swing.JLayeredPane();
        srchbuybtn = new javax.swing.JButton();
        myordersbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mycartbtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        welcomenamelbl = new javax.swing.JLabel();
        searchpane = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        srchpricerb = new javax.swing.JRadioButton();
        srchagerb = new javax.swing.JRadioButton();
        srchnamerb = new javax.swing.JRadioButton();
        searchbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        displabel1 = new javax.swing.JLabel();
        lowertf = new javax.swing.JTextField();
        displabel2 = new javax.swing.JLabel();
        uppertf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        toylist = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        tcodelbl = new javax.swing.JLabel();
        tcodetf = new javax.swing.JTextField();
        tagegrplbl = new javax.swing.JLabel();
        tagegrptf = new javax.swing.JTextField();
        tnamelbl = new javax.swing.JLabel();
        tnametf = new javax.swing.JTextField();
        tdeslbl = new javax.swing.JLabel();
        tdestf = new javax.swing.JTextField();
        tpricelbl = new javax.swing.JLabel();
        tpricetf = new javax.swing.JTextField();
        tqtylbl = new javax.swing.JLabel();
        tqtytf = new javax.swing.JTextField();
        buycb = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        ordqtytf = new javax.swing.JTextField();
        addtocartbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        gotocartbtn = new javax.swing.JButton();
        cartpane = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordtb1 = new javax.swing.JTable();
        totamtlbl = new javax.swing.JLabel();
        totamttf = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        backbtn2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        deletecb1 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        myorderpane = new javax.swing.JLayeredPane();
        placingorderpane = new javax.swing.JLayeredPane();
        image1pane = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        image2pane = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernamelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernamelbl.setText("Username");

        usernametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametfActionPerformed(evt);
            }
        });

        passwordlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordlbl.setText("Password");

        login.setBackground(new java.awt.Color(51, 153, 0));
        login.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LogIn");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Already a Member ?");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("New Here ?");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Create An Account");

        custnamelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custnamelbl.setText("Name");

        custuserlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custuserlbl.setText("Username");

        custpasslbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custpasslbl.setText("Password");

        createaccount.setBackground(new java.awt.Color(51, 153, 0));
        createaccount.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        createaccount.setForeground(new java.awt.Color(255, 255, 255));
        createaccount.setText("Create Account");
        createaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccountActionPerformed(evt);
            }
        });

        Loginpane.setLayer(usernamelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(usernametf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(passwordlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(passwordpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(custnamelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(custuserlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(custpasslbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(custnametf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(custusertf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(createaccount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Loginpane.setLayer(custpasspf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LoginpaneLayout = new javax.swing.GroupLayout(Loginpane);
        Loginpane.setLayout(LoginpaneLayout);
        LoginpaneLayout.setHorizontalGroup(
            LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpaneLayout.createSequentialGroup()
                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginpaneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginpaneLayout.createSequentialGroup()
                                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordpf, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(usernametf)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginpaneLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginpaneLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginpaneLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginpaneLayout.createSequentialGroup()
                                .addComponent(custpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(custpasspf))
                            .addGroup(LoginpaneLayout.createSequentialGroup()
                                .addComponent(custuserlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(custusertf))
                            .addGroup(LoginpaneLayout.createSequentialGroup()
                                .addComponent(custnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(custnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LoginpaneLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(createaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginpaneLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        LoginpaneLayout.setVerticalGroup(
            LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpaneLayout.createSequentialGroup()
                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginpaneLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginpaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginpaneLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(custnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(custnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(custuserlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(custusertf))
                                .addGap(18, 18, 18)
                                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(custpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(custpasspf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(createaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginpaneLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(usernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(LoginpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        srchbuybtn.setBackground(new java.awt.Color(51, 153, 240));
        srchbuybtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        srchbuybtn.setForeground(new java.awt.Color(255, 255, 255));
        srchbuybtn.setText("Search & Buy");
        srchbuybtn.setMaximumSize(new java.awt.Dimension(129, 31));
        srchbuybtn.setMinimumSize(new java.awt.Dimension(129, 31));
        srchbuybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbuybtnActionPerformed(evt);
            }
        });

        myordersbtn.setBackground(new java.awt.Color(51, 153, 240));
        myordersbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        myordersbtn.setForeground(new java.awt.Color(255, 255, 255));
        myordersbtn.setText("My Orders");
        myordersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myordersbtnActionPerformed(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(51, 153, 240));
        logoutbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Logout");
        logoutbtn.setMaximumSize(new java.awt.Dimension(129, 31));
        logoutbtn.setMinimumSize(new java.awt.Dimension(129, 31));
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setText("Search through a wide range of ");

        jLabel7.setText("products like puzzles, electronic toys");

        jLabel12.setText("etc and buy them.");

        jLabel13.setText("See all products you have ordered ");

        jLabel14.setText("along with Total Amount. Also ");

        jLabel15.setText("you can Cancel your order here.");

        mycartbtn.setBackground(new java.awt.Color(51, 153, 240));
        mycartbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        mycartbtn.setForeground(new java.awt.Color(255, 255, 255));
        mycartbtn.setText("My Cart");
        mycartbtn.setMaximumSize(new java.awt.Dimension(129, 31));
        mycartbtn.setMinimumSize(new java.awt.Dimension(129, 31));
        mycartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycartbtnActionPerformed(evt);
            }
        });

        jLabel18.setText("See products waiting in your cart for");

        jLabel19.setText("ordering.");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Welcome,");

        welcomenamelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomenamelbl.setForeground(new java.awt.Color(51, 153, 0));
        welcomenamelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        homepane.setLayer(srchbuybtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(myordersbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(logoutbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(mycartbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homepane.setLayer(welcomenamelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout homepaneLayout = new javax.swing.GroupLayout(homepane);
        homepane.setLayout(homepaneLayout);
        homepaneLayout.setHorizontalGroup(
            homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homepaneLayout.createSequentialGroup()
                        .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srchbuybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homepaneLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(mycartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(homepaneLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(homepaneLayout.createSequentialGroup()
                        .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(myordersbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        homepaneLayout.setVerticalGroup(
            homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepaneLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomenamelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homepaneLayout.createSequentialGroup()
                        .addComponent(myordersbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(homepaneLayout.createSequentialGroup()
                        .addComponent(mycartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(homepaneLayout.createSequentialGroup()
                        .addComponent(srchbuybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homepaneLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(homepaneLayout.createSequentialGroup()
                        .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );

        searchpane.setPreferredSize(new java.awt.Dimension(718, 452));

        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Search Criterion");

        buttonGroup1.add(srchpricerb);
        srchpricerb.setText("Price");
        srchpricerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchpricerbActionPerformed(evt);
            }
        });

        buttonGroup1.add(srchagerb);
        srchagerb.setText("Age");
        srchagerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchagerbActionPerformed(evt);
            }
        });

        buttonGroup1.add(srchnamerb);
        srchnamerb.setText("Name & Category");
        srchnamerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchnamerbActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(51, 153, 240));
        searchbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        displabel1.setText("Enter Lower Limit");

        displabel2.setText("Enter Upper Limit");

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Select Toy Below ");

        toylist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        toylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toylistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(toylist);

        jLabel3.setBackground(new java.awt.Color(204, 0, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("TOY DETAILS");

        tcodelbl.setText("Toy Code");

        tcodetf.setEditable(false);

        tagegrplbl.setText("Age Group");

        tagegrptf.setEditable(false);

        tnamelbl.setText("Name");

        tnametf.setEditable(false);

        tdeslbl.setText("Description");

        tdestf.setEditable(false);

        tpricelbl.setText("Price");

        tpricetf.setEditable(false);

        tqtylbl.setText("Qty in Stock");

        tqtytf.setEditable(false);

        buycb.setText("CLICK ME IF you want to buy this");
        buycb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buycbActionPerformed(evt);
            }
        });

        jLabel10.setText("Order qty");

        ordqtytf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordqtytfActionPerformed(evt);
            }
        });
        ordqtytf.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ordqtytfInputMethodTextChanged(evt);
            }
        });

        addtocartbtn.setBackground(new java.awt.Color(51, 153, 0));
        addtocartbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        addtocartbtn.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn.setText("Add To Cart");
        addtocartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(51, 153, 240));
        backbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        gotocartbtn.setBackground(new java.awt.Color(51, 153, 0));
        gotocartbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        gotocartbtn.setForeground(new java.awt.Color(255, 255, 255));
        gotocartbtn.setText("Go To Cart");
        gotocartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotocartbtnActionPerformed(evt);
            }
        });

        searchpane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(srchpricerb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(srchagerb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(srchnamerb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(searchbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(displabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(lowertf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(displabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(uppertf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tcodelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tcodetf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tagegrplbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tagegrptf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tnamelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tnametf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tdeslbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tdestf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tpricelbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tpricetf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tqtylbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(tqtytf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(buycb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(ordqtytf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(addtocartbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(backbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchpane.setLayer(gotocartbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout searchpaneLayout = new javax.swing.GroupLayout(searchpane);
        searchpane.setLayout(searchpaneLayout);
        searchpaneLayout.setHorizontalGroup(
            searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchpaneLayout.createSequentialGroup()
                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchpaneLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(searchpaneLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchpaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220))
                            .addComponent(jSeparator3)
                            .addGroup(searchpaneLayout.createSequentialGroup()
                                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(searchpaneLayout.createSequentialGroup()
                                        .addComponent(tcodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tcodetf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(tagegrplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tagegrptf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(searchpaneLayout.createSequentialGroup()
                                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tpricelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tdeslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tdestf, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchpaneLayout.createSequentialGroup()
                                                    .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(searchpaneLayout.createSequentialGroup()
                                                            .addComponent(tpricetf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(buycb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(searchpaneLayout.createSequentialGroup()
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(ordqtytf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(searchpaneLayout.createSequentialGroup()
                                                            .addComponent(tqtylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(tqtytf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, searchpaneLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(addtocartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(gotocartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 7, Short.MAX_VALUE))))
                    .addGroup(searchpaneLayout.createSequentialGroup()
                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchpaneLayout.createSequentialGroup()
                                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(searchpaneLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(srchpricerb)
                                        .addGap(103, 103, 103)
                                        .addComponent(srchagerb)
                                        .addGap(127, 127, 127)
                                        .addComponent(srchnamerb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(searchpaneLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(displabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lowertf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(displabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(uppertf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchpaneLayout.setVerticalGroup(
            searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchpaneLayout.createSequentialGroup()
                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srchpricerb)
                            .addComponent(srchagerb)
                            .addComponent(srchnamerb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uppertf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(displabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(displabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lowertf))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchpaneLayout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchpaneLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchpaneLayout.createSequentialGroup()
                                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tcodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tcodetf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tagegrplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tagegrptf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tdeslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tdestf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tpricetf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tqtylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tqtytf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(searchpaneLayout.createSequentialGroup()
                                        .addComponent(tpricelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3)))
                                .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ordqtytf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buycb)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(searchpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addtocartbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addComponent(gotocartbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                            .addComponent(backbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(searchpaneLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        ordtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordtb1.setOpaque(false);
        jScrollPane2.setViewportView(ordtb1);

        totamtlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totamtlbl.setForeground(new java.awt.Color(204, 0, 51));
        totamtlbl.setText("Total Amount Payable ( ₹)");

        totamttf.setEditable(false);

        submitbtn.setBackground(new java.awt.Color(51, 153, 0));
        submitbtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Place Order");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        backbtn2.setBackground(new java.awt.Color(51, 153, 240));
        backbtn2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        backbtn2.setForeground(new java.awt.Color(255, 255, 255));
        backbtn2.setText("Back");
        backbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("My Cart");

        homebtn.setBackground(new java.awt.Color(51, 153, 240));
        homebtn.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setText("Home");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        deletecb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecb1ActionPerformed(evt);
            }
        });

        jLabel17.setText("* Click the Check Box to Delete Item.");

        cartpane.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(totamtlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(totamttf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(submitbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(backbtn2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(homebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(deletecb1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cartpane.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout cartpaneLayout = new javax.swing.GroupLayout(cartpane);
        cartpane.setLayout(cartpaneLayout);
        cartpaneLayout.setHorizontalGroup(
            cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartpaneLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartpaneLayout.createSequentialGroup()
                        .addGroup(cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cartpaneLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cartpaneLayout.createSequentialGroup()
                                .addComponent(totamtlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totamttf, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(cartpaneLayout.createSequentialGroup()
                                .addComponent(deletecb1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartpaneLayout.createSequentialGroup()
                        .addComponent(backbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        cartpaneLayout.setVerticalGroup(
            cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(cartpaneLayout.createSequentialGroup()
                        .addComponent(homebtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartpaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartpaneLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(deletecb1)))
                .addGap(5, 5, 5)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totamtlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totamttf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(cartpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout myorderpaneLayout = new javax.swing.GroupLayout(myorderpane);
        myorderpane.setLayout(myorderpaneLayout);
        myorderpaneLayout.setHorizontalGroup(
            myorderpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        myorderpaneLayout.setVerticalGroup(
            myorderpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout placingorderpaneLayout = new javax.swing.GroupLayout(placingorderpane);
        placingorderpane.setLayout(placingorderpaneLayout);
        placingorderpaneLayout.setHorizontalGroup(
            placingorderpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        placingorderpaneLayout.setVerticalGroup(
            placingorderpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample/WhatsApp-Image-20160725(1).jpeg"))); // NOI18N

        image1pane.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout image1paneLayout = new javax.swing.GroupLayout(image1pane);
        image1pane.setLayout(image1paneLayout);
        image1paneLayout.setHorizontalGroup(
            image1paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        image1paneLayout.setVerticalGroup(
            image1paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sample/Yellow-Background-HD.jpg"))); // NOI18N

        image2pane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout image2paneLayout = new javax.swing.GroupLayout(image2pane);
        image2pane.setLayout(image2paneLayout);
        image2paneLayout.setHorizontalGroup(
            image2paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        image2paneLayout.setVerticalGroup(
            image2paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Loginpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cartpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homepane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(myorderpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(placingorderpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(image1pane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(image2pane, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Loginpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cartpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homepane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(myorderpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(placingorderpane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(image1pane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(image2pane, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametfActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

    if(usernametf.getText().isEmpty())
{JOptionPane.showMessageDialog(null, "please enter username");}
    else if(passwordpf.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "please enter password");
    }

     if(usernametf.getText().length()!=0 && passwordpf.getText().length()!=0)
     {
         String query1="select username,password,customername from customer where username='"+usernametf.getText()+"';";
         System.out.println(query1);
         String user="";
         String pass="";
         String custname="";
         try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/karan","root","");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(query1);
            while(rs.next())
            {
                 user=rs.getString("username");
                 pass=rs.getString("password");
                 custname=rs.getString("customername");
            }
            System.out.println(user+" and "+pass);
            if((usernametf.getText().equals(user))&&(passwordpf.getText().equals(pass)))
            {
                Loginpane.setVisible(false);
                homepane.setVisible(true);
                searchpane.setVisible(false);
                cartpane.setVisible(false);
                myorderpane.setVisible(false);
                placingorderpane.setVisible(false);
                image1pane.setVisible(true);
                image2pane.setVisible(false);
                welcomenamelbl.setText(custname);
            }
             else {
        JOptionPane.showMessageDialog(null, "incorrect username or password");
        usernametf.setText("");
        passwordpf.setText("");
    }
         }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"Error in connectivity");
        }
        catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error in connectivity sql");

        }
     }
   
       
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void srchnamerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchnamerbActionPerformed
        if(srchnamerb.isSelected())
        {
            lowertf.setText("");
            uppertf.setText("");
            displabel1.setText("Enter Name");
            
            displabel2.setEnabled(false);
            uppertf.setEnabled(false);
        }
        else
        {
            lowertf.setText("");
            uppertf.setText("");
            displabel1.setText("Enter Lower Limit");
            displabel2.setEnabled(true);
            uppertf.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_srchnamerbActionPerformed
    int price;
    private void addtocartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtnActionPerformed

        int qtya=Integer.parseInt(tqtytf.getText());
        int qtyo=Integer.parseInt(ordqtytf.getText());
        if(qtyo>qtya)
        {
            JOptionPane.showMessageDialog(rootPane,"Sorry, Cannot take "
                    + "your Order");
        }
        else
        {
            
            int tprice=Integer.parseInt(tpricetf.getText());
            System.out.println(""+tprice);
            int amt=qtyo*tprice;
            System.out.println(""+amt);
            price=price+amt;
            System.out.println("total price ="+price);
            int tc= Integer.parseInt(tcodetf.getText());
            System.out.println(""+tc);
  String qry="Update toys set qtyinstock = qtyinstock - "+qtyo+" where toycode="+tc+";";
  String qry1="Select toycode,name,price from toys where toycode="+tc+";";
            System.out.println(qry+"");
            try{
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/karan","root","");
                
                System.out.println("connection created");
                
                
                Statement stmt=con.createStatement();
//                stmt.executeUpdate(qry);
                ResultSet rs=stmt.executeQuery(qry1);
               
                 System.out.println("query executed");
                while(rs.next())
                {
                     Object o[]= {rs.getInt(1), rs.getString(2), rs.getInt(3), qtyo,
             amt};
                    
                model1.addRow(o);
                ordtb1.setModel(model1);
                }
                  JOptionPane.showMessageDialog(null,"Item added to your Cart.");
            }catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null,"Error in connectivity");
            }
            catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error in connectivity sql");

        }
            ordqtytf.setText("");
            ordqtytf.setEnabled(false);
            buycb.setSelected(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_addtocartbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        emptylist();
        String filter="";
        
        if(buttonGroup1.isSelected(null)){
            JOptionPane.showMessageDialog(null, "Please select.");
        }
        else{
        if(srchnamerb.isSelected())
        {
            System.out.println("hello");
            filter="where name='"+lowertf.getText()+"'";
            System.out.println(""+filter);
        }
        else if(srchpricerb.isSelected())
        {
            int pricel=Integer.parseInt(lowertf.getText());
            int pricef=Integer.parseInt(uppertf.getText());
            filter="where price>="+pricel+" and price<="+pricef;
        }
        else if(srchagerb.isSelected())
        {
            int agel=Integer.parseInt(lowertf.getText());
            //int agef=Integer.parseInt(uppertf.getText());
            filter="where agegrouplowerlimit="+agel;
        }
        
        int count=0;
        String query="Select name from toys "+filter+";";
  
            toylist.setModel(model);
      
        System.out.println("Hello in search");
        System.out.println(""+query);
        try{
            Class.forName("java.sql.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"karan","root","");
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                String s;
                while(rs.next())
                {
                    s=rs.getString("name");
                    System.out.println(""+s);
                   model.add(count,rs.getString("name"));
                    count++;
              
                }
                rs.close();
                stmt.close();
                con.close();
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"Error in connectivity");
        }
        catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error in connectivity sql");

        }
        ordqtytf.setEnabled(false);        
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_searchbtnActionPerformed

    private void srchagerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchagerbActionPerformed
        if(srchagerb.isSelected())
        {
            lowertf.setText("");
            uppertf.setText("");
            displabel1.setText("Enter age lower");
            displabel2.setText("Enter age Upper");
            displabel2.setEnabled(true);
            uppertf.setEnabled(true);
        }
        else
        {
            lowertf.setText("");
            uppertf.setText("");
            displabel1.setText("Enter Lower Limit");
            displabel2.setEnabled(true);
            uppertf.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_srchagerbActionPerformed

    private void backbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn2ActionPerformed
            Loginpane.setVisible(false);
        homepane.setVisible(false);
        searchpane.setVisible(true);
        cartpane.setVisible(false);
        myorderpane.setVisible(false);
        placingorderpane.setVisible(false);
        image1pane.setVisible(false);
        image2pane.setVisible(true);
           

        // TODO add your handling code here:
    }//GEN-LAST:event_backbtn2ActionPerformed

    private void buycbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buycbActionPerformed
        if(buycb.isSelected())
        {
            ordqtytf.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buycbActionPerformed

    private void srchpricerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchpricerbActionPerformed
        if(srchpricerb.isSelected())
        {
            lowertf.setText("");
            uppertf.setText("");
            displabel1.setText("Enter lower limit");
            displabel2.setText("Enter Upper limit");
            displabel2.setEnabled(true);
            uppertf.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_srchpricerbActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
       
        int count=model1.getRowCount();
        String total=totamttf.getText();
        JOptionPane.showMessageDialog(rootPane,"You have orderd for "+count+
                " items. \nYour Bill Amount is Rs. "+total+"\n");
        // TODO add your handling code here:
    }//GEN-LAST:event_submitbtnActionPerformed

    private void toylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toylistMouseClicked
        // TODO add your handling code here:
         String selval=toylist.getSelectedValue();
        String query="Select * from toys where name='"+selval+"';";
        try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql:"
                        + "//localhost:3306/karan","root","");
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                rs.next();
                {
                    tcodetf.setText(""+rs.getInt(1));
                    tnametf.setText(rs.getString(2));
                    tdestf.setText(rs.getString(3));
                    tqtytf.setText(""+rs.getInt(4));
                    tagegrptf.setText(""+rs.getInt(5)+" to "+rs.getInt(6));
                    tpricetf.setText(""+rs.getInt(8));
                }
                rs.close();
                stmt.close();
                
                con.close();
            
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error in connectivity");
    }
    
    }//GEN-LAST:event_toylistMouseClicked

    private void ordqtytfInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ordqtytfInputMethodTextChanged
    }//GEN-LAST:event_ordqtytfInputMethodTextChanged

    private void ordqtytfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordqtytfActionPerformed

    }//GEN-LAST:event_ordqtytfActionPerformed

    private void createaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccountActionPerformed
        if(custnametf.getText().isEmpty() || custusertf.getText().isEmpty() || custpasspf.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Fill all the fields.");
        } 
        else
        {
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/karan","root","");
            Statement stmt=con.createStatement();
            String query="Insert into customer values('"+custnametf.getText()+"','"+custusertf.getText()+"','"+custpasspf.getText()+"',NULL,NULL,NULL);";
            System.out.println(query);
            stmt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null,"Account Created Successfully.\n Click OK to LogIn.");
            custnametf.setText("");
            custusertf.setText("");
            custpasspf.setText("");
        }catch(ClassNotFoundException e)
        {
            System.out.println("Error in connectivity");
        }catch(SQLException e){
            System.out.println("Error in connectivity sql");
            JOptionPane.showMessageDialog(null,"Username already taken.");
        }catch(HeadlessException e){
            System.out.println("Error in connectivity headless exception");
        }
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_createaccountActionPerformed

    private void srchbuybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbuybtnActionPerformed
        Loginpane.setVisible(false);
        searchpane.setVisible(true);
        cartpane.setVisible(false);
       
        homepane.setVisible(false);
        image1pane.setVisible(false);
        image2pane.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_srchbuybtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        Loginpane.setVisible(true);
        searchpane.setVisible(false);
        cartpane.setVisible(false);
       
        homepane.setVisible(false);
        image1pane.setVisible(true);
        image2pane.setVisible(false);
        usernametf.setText("");
        passwordpf.setText("");
        custnametf.setText("");
        custusertf.setText("");
        custpasspf.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Loginpane.setVisible(false);
        searchpane.setVisible(false);
        cartpane.setVisible(false);
        
        homepane.setVisible(true);
        image1pane.setVisible(true);
            image2pane.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    private void myordersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myordersbtnActionPerformed

        Loginpane.setVisible(false);
        searchpane.setVisible(false);
        cartpane.setVisible(false);
       
        homepane.setVisible(false);
        myorderpane.setVisible(true);
        image1pane.setVisible(false);
            image2pane.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_myordersbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed

        Loginpane.setVisible(false);
        searchpane.setVisible(false);
        cartpane.setVisible(false);
       
        homepane.setVisible(true);
        myorderpane.setVisible(false);
        image1pane.setVisible(true);
        image2pane.setVisible(false);
        emptylist();
        buttonGroup1.clearSelection();
        lowertf.setText("");
        uppertf.setText("");
        tcodetf.setText("");
        tagegrptf.setText("");
        tnametf.setText("");
        tdestf.setText("");
        tpricetf.setText("");
        tqtytf.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_homebtnActionPerformed

    private void deletecb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecb1ActionPerformed
        if(deletecb1.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Delete this item.");
            model1.removeRow(0);
            deletecb1.setEnabled(false);
            deletecb1.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deletecb1ActionPerformed

    private void mycartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycartbtnActionPerformed

        Loginpane.setVisible(false);
        searchpane.setVisible(false);
        cartpane.setVisible(true);
       
        homepane.setVisible(false);
        myorderpane.setVisible(false);
        image1pane.setVisible(false);
        image2pane.setVisible(true);
        if(ordtb1.getRowCount()==0)
        {
             JOptionPane.showMessageDialog(null,"Your Cart is Empty right now.");
              Loginpane.setVisible(false);
                homepane.setVisible(true);
                searchpane.setVisible(false);
                cartpane.setVisible(false);
                myorderpane.setVisible(false);
                placingorderpane.setVisible(false);
                image1pane.setVisible(true);
                image2pane.setVisible(false);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mycartbtnActionPerformed

    private void gotocartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotocartbtnActionPerformed

        totamttf.setText(""+price);
        Loginpane.setVisible(false);
            searchpane.setVisible(false);
            cartpane.setVisible(true);
            image1pane.setVisible(false);
            image2pane.setVisible(true);
            deletecb1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_gotocartbtnActionPerformed

    void emptylist()
 {
        while(model.getSize()>0)
        {
            model.remove(0);
        }
    }
  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LegoStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LegoStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LegoStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LegoStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LegoStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Loginpane;
    private javax.swing.JButton addtocartbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton backbtn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox buycb;
    private javax.swing.JLayeredPane cartpane;
    private javax.swing.JButton createaccount;
    private javax.swing.JLabel custnamelbl;
    private javax.swing.JTextField custnametf;
    private javax.swing.JLabel custpasslbl;
    private javax.swing.JPasswordField custpasspf;
    private javax.swing.JLabel custuserlbl;
    private javax.swing.JTextField custusertf;
    private javax.swing.JCheckBox deletecb1;
    private javax.swing.JLabel displabel1;
    private javax.swing.JLabel displabel2;
    private javax.swing.JButton gotocartbtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLayeredPane homepane;
    private javax.swing.JLayeredPane image1pane;
    private javax.swing.JLayeredPane image2pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton login;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JTextField lowertf;
    private javax.swing.JButton mycartbtn;
    private javax.swing.JLayeredPane myorderpane;
    private javax.swing.JButton myordersbtn;
    private javax.swing.JTextField ordqtytf;
    private javax.swing.JTable ordtb1;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JPasswordField passwordpf;
    private javax.swing.JLayeredPane placingorderpane;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLayeredPane searchpane;
    private javax.swing.JRadioButton srchagerb;
    private javax.swing.JButton srchbuybtn;
    private javax.swing.JRadioButton srchnamerb;
    private javax.swing.JRadioButton srchpricerb;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel tagegrplbl;
    private javax.swing.JTextField tagegrptf;
    private javax.swing.JLabel tcodelbl;
    private javax.swing.JTextField tcodetf;
    private javax.swing.JLabel tdeslbl;
    private javax.swing.JTextField tdestf;
    private javax.swing.JLabel tnamelbl;
    private javax.swing.JTextField tnametf;
    private javax.swing.JLabel totamtlbl;
    private javax.swing.JTextField totamttf;
    private javax.swing.JList<String> toylist;
    private javax.swing.JLabel tpricelbl;
    private javax.swing.JTextField tpricetf;
    private javax.swing.JLabel tqtylbl;
    private javax.swing.JTextField tqtytf;
    private javax.swing.JTextField uppertf;
    private javax.swing.JLabel usernamelbl;
    private javax.swing.JTextField usernametf;
    private javax.swing.JLabel welcomenamelbl;
    // End of variables declaration//GEN-END:variables
}
